### ISSUE TITLE
Update only a single year

### ISSUE THREAD

**Issue by MindTooth** [p3lim/license-year-updater#5]
Hi,

Thank you for this nice action. 👍🏻   I just tried it out, and it didn't really behave has I wanted.  Main issue, is that I don't want to increase the range, just bump the same year.

Is this somewhat that is trivial to implement?

---

## Expected behavior

```patch
- Copyright © 2022 <name> <email>
+ Copyright © 2023 <name> <email>
```

**Comment by p3lim** [comment]
Should be available in v2.1, please give it a try.
